__author__ = 'Alex Geary'

"""Parameters used throughout OpenPinch. These parameters are assigned default values in this 
and able to be modified through a user interface by the user.
"""

COSTING_OPTIONSFORM_FC = 0
COSTING_OPTIONSFORM_VC = 10000
COSTING_OPTIONSFORM_EXP = 0.7
COSTING_OPTIONSFORM_DISCOUNT_RATE = 0.07
COSTING_OPTIONSFORM_SERV_LIFE = 10
COSTING_OPTIONSFORM_ANNUAL_OP_TIME = 8300

DEFAULT_DTCONT = 10
DEFAULT_HTC = 1.0
DEFAULTFORM_UTILITY_PRICE = 40
DEFAULTFORM_TEMP_REF = 15
DEFAULTFORM_PRESSURE_REF = 101
DEFAULTFORM_AHT_BUTTON_SELECTED = False
DEFAULTFORM_OVERRIDEDT_BUTTON_SELECTED = False

GRAPH_OPTIONSFORM_CC_CHECKBOX = True
GRAPH_OPTIONSFORM_SCC_CHECKBOX = True
GRAPH_OPTIONSFORM_GCC_CHECKBOX = True
GRAPH_OPTIONSFORM_BCC_CHECKBOX = False
GRAPH_OPTIONSFORM_GCC_NP_CHECKBOX = False
GRAPH_OPTIONSFORM_GCCU_CHECKBOX = True
GRAPH_OPTIONSFORM_TSC_CHECKBOX = False
GRAPH_OPTIONSFORM_LGCC_CHECKBOX = False
GRAPH_OPTIONSFORM_ADVCC_CHECKBOX = False
GRAPH_OPTIONSFORM_KW_OPTION = True
GRAPH_OPTIONSFORM_MW_OPTION = False
GRAPH_OPTIONSFORM_GW_OPTION = False
GRAPH_OPTIONSFORM_DECOLOR_BUTTON = False

HXFORM_CF_SELECTED = True
HXFORM_PF_SELECTED = False
SHELL_AND_TUBE = False

RETROFITFORM_HHT_OPTION = True
RETROFITFORM_VHT_OPTION = False
RETROFITFORM_AUTOREORDER = False
RETROFITFORM_AUTOREORDER_1 = False
RETROFITFORM_AUTOREORDER_2 = False
RETROFITFORM_AUTOREORDER_3 = False
RETROFITFORM_AUTOREORDER_4 = False
RETROFITFORM_GCC_REG_FULL_POCKET = True
RETROFITFORM_GCC_VERT_CUT_KINK_OPTION = False
RETROFITFORM_SET_MIN_DH_THRES = False
RETROFITFORM_SET_MIN_TH_AREA = False
RETROFITFORM_AUTOMATED_RETROFIT_TARGETING_BUTTON = False
RETROFITFORM_THRESHOLD = 0
RETROFITFORM_AREA_THRESHOLD = 0

RETROFIT_OPTIONSFORM_Q_MIN = 400
RETROFIT_OPTIONSFORM_NUM_HX = 6
RETROFIT_OPTIONSFORM_AREA_RATIO = 0
RETROFIT_OPTIONSFORM_PRICE_UTILITIES = 220
RETROFIT_OPTIONSFORM_MAX_RBBRIDGE = 100000
RETROFIT_OPTIONSFORM_RECORD = True
RETROFIT_OPTIONSFORM_PARETO = False
RETROFIT_OPTIONSFORM_QUANTIFY_AREA = False
RETROFIT_OPTIONSFORM_ACCELERATION = True
RETROFIT_OPTIONSFORM_HEURISTICS = True

SETTINGSFORM_TIT_BUTTON_SELECTED = False
SETTINGSFORM_TS_BUTTON_SELECTED = False
SETTINGSFORM_TURBINE_WORK_BUTTON = False
SETTINGSFORM_AREA_BUTTON = False
SETTINGSFORM_ENERGY_RETROFIT_BUTTON = False
SETTINGSFORM_EXERGY_BUTTON = False
SETTINGSFORM_PRINT_PTS = False
SETTINGSFORM_PLOT_GRAPHS = False

TURBINE_MODELS = (
    'Medina-Flores et al. (2010)',
    'Sun & Smith (2015)',
    'Varbanov et al. (2004)',
    'Fixed Isentropic Turbine'
)

TURBINEFORM_T_TURBINE_BOX = 450
TURBINEFORM_P_TURBINE_BOX = 90
TURBINEFORM_MIN_EFF = 0.1
TURBINEFORM_ELECTRICITY_PRICE = 100 # $/MWh
TURBINEFORM_LOAD = 1.0
TURBINEFORM_MECH_EFF = 1.0
TURBINEFORM_COMBOBOX = TURBINE_MODELS[0]
TURBINEFORM_ABOVE_PINCH_CHECKBOX = True
TURBINEFORM_BELOW_PINCH_CHECKBOX = False
TURBINEFORM_CONDESATE_FLASH_CORRECTION = False
