name: Run Pytest

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: |
        uv sync --dev
    
    - name: Add solvers to path
      run: |
        echo "PATH=$PATH:$PWD/solvers" >> $GITHUB_ENV

    - name: Run fast tests
      run: |
        uv run pytest -m "not solver"
